defaultPlacement: end
enableVersioning: false
handle: datenschutzerklaerung
name: Datenschutzerkl√§rung
propagationMethod: all
siteSettings:
  20bbb0e3-e6b3-4759-831d-183394189075: # Ferienwohnung Dornumersiel
    enabledByDefault: true
    hasUrls: true
    template: text-only.twig
    uriFormat: datenschutzerklaerung
type: single
